api_platform:
    title: 'Chroniques Oubliées API'
    version: '1.0.0'
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
    docs_formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
        pagination_client_enabled: true
        pagination_client_items_per_page: true
        pagination_items_per_page: 30
        pagination_maximum_items_per_page: 1000
    enable_swagger_ui: true
    enable_re_doc: true
    enable_docs: true
    enable_entrypoint: true
