<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Nettoyage du bestiaire officiel : décision produit du 2026-09-27, on ne garde que ce
 * qui est un vrai bloc de stats nommé dans le livre de base (doc/getRulesFullToMD/
 * partie3-mj/03-bestiaire-opposition.md), vérifié stat par stat avec scripts/audit-
 * bestiaire.mjs (80 profils du livre, 0 divergence après cette migration).
 *
 * Supprime 147 créatures sans aucune correspondance numérique avec le livre (constaté
 * en comparant, pas en devinant : par exemple la base servait « Ogre » NC3/DEF16/PV30,
 * le livre donne « Ogre de base » NC3/DEF17/PV40 — proche mais pas le même bloc). Ajoute
 * les 9 profils du livre qui manquaient (dont Chimère draconique, qui hérite des stats
 * de Chimère avec un souffle en plus — non compté par l'audit faute de bloc de
 * Caractéristiques propre, mais bien un profil nommé du livre).
 *
 * backend/data/creatures.json déjà mis à jour en parallèle (source pour les futurs
 * environnements/CI). creature_voie n'a aucune ligne à ce jour pour les créatures
 * supprimées (vérifié), mais le DELETE défensif reste au cas où.
 */
final class Version20260927140000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Bestiaire : ne garde que les créatures officielles du livre de base (147 supprimées, 9 ajoutées)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("DELETE FROM creature_voie WHERE creature_id IN (SELECT id FROM creature WHERE name IN ('Ange', 'Ankheg', 'Aigle', 'Aigle géant', 'Roc', 'Barghest', 'Béhir', 'Bulette', 'Calmar géant', 'Centaure', 'Centaure Rôdeur niveau 4', 'Chauve-souris géante', 'Cheval de guerre léger', 'Cheval de guerre lourd', 'Chien infernal', 'Molosse satanique', 'Cockatrice', 'Crocodile géant', 'Cube gélatineux', 'Balor', 'Marilith', 'Quasit', 'Succube', 'Destrier noir', 'Diplodocus', 'Deinonychus', 'Ptéranodon', 'Triceratops', 'Tyrannosaure', 'Doppleganger', 'Dragon juvénile', 'Dragon jeune', 'Dragon adulte', 'Dragon ancien', 'Drider', 'Dryade', 'Elémentaire d''air, petit', 'Elémentaire d''air, moyen', 'Elémentaire d''air, grand', 'Elémentaire d''air, énorme', 'Elémentaire d''air, colossal', 'Elémentaire d''eau, petit', 'Elémentaire d''eau, moyen', 'Elémentaire d''eau, énorme', 'Elémentaire d''eau, colossal', 'Elémentaire de feu, petit', 'Elémentaire de feu, moyen', 'Elémentaire de feu, grand', 'Elémentaire de feu, énorme', 'Elémentaire de feu, colossal', 'Elémentaire de terre, petit', 'Elémentaire de terre, moyen', 'Elémentaire de terre, grand', 'Elémentaire de terre, énorme', 'Elémentaire de terre, colossal', 'Mammouth', 'Elfe des bois', 'Guerrier elfe noir', 'Guerrière elfe noir', 'Prêtresse elfe noir', 'Ettin', 'Fantôme mineur', 'Fantôme majeur', 'Gargouille', 'Géant des collines', 'Géant de pierre', 'Géant du givre', 'Géant des tempêtes', 'Djinn', 'Efrit', 'Gobelours', 'Golem de pierre', 'Golem de fer', 'Gorille géant', 'Harpie', 'Hippogriffe', 'Hobgobelin de base', 'Capitaine hobgobelin', 'Homme-lézard de base', 'Champion homme-lézard', 'Hydre à 10 têtes', 'Insecte de taille petite', 'Insecte de taille moyenne', 'Insecte de taille grande', 'Insecte de taille énorme', 'Insecte de taille colossale', 'Liche', 'Grand mâle, lion', 'Tigre', 'Tigre à dents de sabre', 'Loup géant', 'Loup arctique', 'Loup-garou infecté', 'Loup-garou naturel', 'Rat-garou infecté', 'Rat-garou naturel', 'Manticore', 'Méduse', 'Minotaure', 'Champion minotaure', 'Naga maléfique', 'Naga neutre', 'Naga bon', 'Nain', 'Nain sombre', 'Nuée de rats', 'Nuée d''oiseaux', 'Nuée de frelons', 'Nuée d''araignées venimeuses', 'Nuée de guêpes géantes', 'Nymphe', 'Ogre', 'Ogre mage', 'Orque', 'Orque élite', 'Ours préhistorique', 'Ours-hibou', 'Pégase', 'Pieuvre géante', 'Pixie', 'Pixie ensorceleur', 'Sanglier sanguinaire', 'Serpent géant', 'Spectre', 'Strige', 'Sylvanien', 'Taureau', 'Taureau, grand mâle', 'Titan', 'Wiverne', 'Ours hibou zombi', 'Gamin', 'Passant', 'Marchand', 'Soldat', 'Sergent', 'Garde d''élite', 'Voleur à la tire', 'Surineur', 'Gros bras', 'Spadassin', 'Assassin mineur', 'Assassin majeur', 'Maître assassin', 'Grand maître assassin', 'Créature minuscule', 'Créature très petite'))");
        $this->addSql("DELETE FROM creature WHERE name IN ('Ange', 'Ankheg', 'Aigle', 'Aigle géant', 'Roc', 'Barghest', 'Béhir', 'Bulette', 'Calmar géant', 'Centaure', 'Centaure Rôdeur niveau 4', 'Chauve-souris géante', 'Cheval de guerre léger', 'Cheval de guerre lourd', 'Chien infernal', 'Molosse satanique', 'Cockatrice', 'Crocodile géant', 'Cube gélatineux', 'Balor', 'Marilith', 'Quasit', 'Succube', 'Destrier noir', 'Diplodocus', 'Deinonychus', 'Ptéranodon', 'Triceratops', 'Tyrannosaure', 'Doppleganger', 'Dragon juvénile', 'Dragon jeune', 'Dragon adulte', 'Dragon ancien', 'Drider', 'Dryade', 'Elémentaire d''air, petit', 'Elémentaire d''air, moyen', 'Elémentaire d''air, grand', 'Elémentaire d''air, énorme', 'Elémentaire d''air, colossal', 'Elémentaire d''eau, petit', 'Elémentaire d''eau, moyen', 'Elémentaire d''eau, énorme', 'Elémentaire d''eau, colossal', 'Elémentaire de feu, petit', 'Elémentaire de feu, moyen', 'Elémentaire de feu, grand', 'Elémentaire de feu, énorme', 'Elémentaire de feu, colossal', 'Elémentaire de terre, petit', 'Elémentaire de terre, moyen', 'Elémentaire de terre, grand', 'Elémentaire de terre, énorme', 'Elémentaire de terre, colossal', 'Mammouth', 'Elfe des bois', 'Guerrier elfe noir', 'Guerrière elfe noir', 'Prêtresse elfe noir', 'Ettin', 'Fantôme mineur', 'Fantôme majeur', 'Gargouille', 'Géant des collines', 'Géant de pierre', 'Géant du givre', 'Géant des tempêtes', 'Djinn', 'Efrit', 'Gobelours', 'Golem de pierre', 'Golem de fer', 'Gorille géant', 'Harpie', 'Hippogriffe', 'Hobgobelin de base', 'Capitaine hobgobelin', 'Homme-lézard de base', 'Champion homme-lézard', 'Hydre à 10 têtes', 'Insecte de taille petite', 'Insecte de taille moyenne', 'Insecte de taille grande', 'Insecte de taille énorme', 'Insecte de taille colossale', 'Liche', 'Grand mâle, lion', 'Tigre', 'Tigre à dents de sabre', 'Loup géant', 'Loup arctique', 'Loup-garou infecté', 'Loup-garou naturel', 'Rat-garou infecté', 'Rat-garou naturel', 'Manticore', 'Méduse', 'Minotaure', 'Champion minotaure', 'Naga maléfique', 'Naga neutre', 'Naga bon', 'Nain', 'Nain sombre', 'Nuée de rats', 'Nuée d''oiseaux', 'Nuée de frelons', 'Nuée d''araignées venimeuses', 'Nuée de guêpes géantes', 'Nymphe', 'Ogre', 'Ogre mage', 'Orque', 'Orque élite', 'Ours préhistorique', 'Ours-hibou', 'Pégase', 'Pieuvre géante', 'Pixie', 'Pixie ensorceleur', 'Sanglier sanguinaire', 'Serpent géant', 'Spectre', 'Strige', 'Sylvanien', 'Taureau', 'Taureau, grand mâle', 'Titan', 'Wiverne', 'Ours hibou zombi', 'Gamin', 'Passant', 'Marchand', 'Soldat', 'Sergent', 'Garde d''élite', 'Voleur à la tire', 'Surineur', 'Gros bras', 'Spadassin', 'Assassin mineur', 'Assassin majeur', 'Maître assassin', 'Grand maître assassin', 'Créature minuscule', 'Créature très petite')");
        $this->addSql("INSERT INTO creature (name, description, nc, hp, def, init, stats, special_abilities, attacks, capabilities, picture, category, environment, archetype, size, stats_superior, family_id) VALUES ('Aigle commun', 'Ce profil correspond à tous les oiseaux de proie de grande taille (environ 2 m d''envergure).', 0.5, 3, 13, 16, '{\"AGI\":3,\"CON\":2,\"FOR\":-3,\"PER\":4,\"CHA\":0,\"INT\":-4,\"VOL\":0}', '{\"text\":\"Vol rapide. La créature obtient une action de mouvement supplémentaire par round lorsqu''elle est en vol. Au premier round de combat, la créature obtient un dé bonus en attaque et +1d4 aux DM si elle est en vol et attaque une créature au sol.\\nEmporter dans les airs. La créature peut emporter dans les airs une créature de taille minuscule ou moins. En cas de chute, les créatures de taille minuscule subissent seulement 1 DM par dé de chute (au lieu de 1d4°).\"}', '[{\"name\":\"Serres\",\"test\":\"+3\",\"dm\":\"1d4\",\"special\":null,\"reach\":null}]', '[]', NULL, 'Vivante', NULL, NULL, 'Petite', '[\"AGI\",\"PER\"]', (SELECT id FROM creature_family WHERE name = 'Aigles'))");
        $this->addSql("INSERT INTO creature (name, description, nc, hp, def, init, stats, special_abilities, attacks, capabilities, picture, category, environment, archetype, size, stats_superior, family_id) VALUES ('Animal minuscule', 'Exemple : souris.', 0, 1, 13, 16, '{\"AGI\":3,\"CON\":-4,\"FOR\":-4,\"PER\":2,\"CHA\":-2,\"INT\":-4,\"VOL\":-2}', '{\"text\":\"Minuscule. La créature obtient un bonus de +10 aux tests d''escalade et de discrétion.\\nAttaques ridicules. La créature n''inflige pas de DM sauf sur une réussite critique (1 DM).\"}', '[{\"name\":\"Morsure\",\"test\":\"+1\",\"dm\":\"0\",\"special\":null,\"reach\":null}]', '[]', NULL, 'Vivante', NULL, NULL, 'Minuscule', '[\"AGI\",\"PER\"]', NULL)");
        $this->addSql("INSERT INTO creature (name, description, nc, hp, def, init, stats, special_abilities, attacks, capabilities, picture, category, environment, archetype, size, stats_superior, family_id) VALUES ('Animal très petit', 'Exemple : chat.', 0, 2, 13, 16, '{\"AGI\":3,\"CON\":-3,\"FOR\":-3,\"PER\":2,\"CHA\":-2,\"INT\":-4,\"VOL\":0}', '{\"text\":\"Très petit. La créature obtient un bonus de +5 aux tests d''escalade et de discrétion.\"}', '[{\"name\":\"Morsure\",\"test\":\"+2\",\"dm\":\"1\",\"special\":null,\"reach\":null}]', '[]', NULL, 'Vivante', NULL, NULL, 'Très petite', '[\"AGI\",\"PER\"]', NULL)");
        $this->addSql("INSERT INTO creature (name, description, nc, hp, def, init, stats, special_abilities, attacks, capabilities, picture, category, environment, archetype, size, stats_superior, family_id) VALUES ('Animal petit', 'Exemple : gros chien. L''aigle possède son propre profil.', 0, 3, 13, 15, '{\"AGI\":2,\"CON\":-2,\"FOR\":-2,\"PER\":2,\"CHA\":-2,\"INT\":-4,\"VOL\":0}', NULL, '[{\"name\":\"Morsure\",\"test\":\"+3\",\"dm\":\"1d6-2\",\"special\":null,\"reach\":null}]', '[]', NULL, 'Vivante', NULL, NULL, 'Petite', '[\"AGI\",\"PER\"]', NULL)");
        $this->addSql("INSERT INTO creature (name, description, nc, hp, def, init, stats, special_abilities, attacks, capabilities, picture, category, environment, archetype, size, stats_superior, family_id) VALUES ('Cheval de guerre', '', 1, 14, 11, 10, '{\"AGI\":0,\"CON\":4,\"FOR\":5,\"PER\":0,\"CHA\":-1,\"INT\":-4,\"VOL\":0}', '{\"text\":\"Monture. La créature double sa FOR pour porter une charge. Un cheval de guerre est apte à porter une barde, un ensemble de protections pour lui. Un caparaçon de maille augmente la DEF du cheval de +2 pour un prix de 100 pa. Une barde de plaques de métal apporte un bonus de +4 en DEF pour un prix de 400 pa. Les bardes font subir au cheval et à son cavalier un malus en Init. égal au bonus de DEF.\"}', '[{\"name\":\"Ruade\",\"test\":\"+4\",\"dm\":\"1d4+5\",\"special\":null,\"reach\":null}]', '[]', NULL, 'Vivante', NULL, NULL, 'Grande', '[\"CON\"]', (SELECT id FROM creature_family WHERE name = 'Chevaux'))");
        $this->addSql("INSERT INTO creature (name, description, nc, hp, def, init, stats, special_abilities, attacks, capabilities, picture, category, environment, archetype, size, stats_superior, family_id) VALUES ('Ogre de base', 'L''ogre est une brute épaisse mesurant plus de 2,50 m (pour 300 kg). Cette créature maléfique a un penchant pour les armes démesurées et la boucherie gratuite. C''est un adversaire formidable et un combat contre un ogre n''est jamais sans risque. Il parle le noir parler et parfois le commun.', 3, 40, 17, 10, '{\"AGI\":1,\"CON\":6,\"FOR\":6,\"PER\":0,\"CHA\":-2,\"INT\":-2,\"VOL\":0}', '{\"text\":\"Une capacité au choix parmi Tape dur ou Imparable.\\nTape dur. Si la créature obtient 15 à 20 au dé du test d''attaque, l''attaque est automatiquement réussie. De surcroît, la victime doit réussir un test de CON difficulté 16 ou être étourdie pendant 1 round.\\nImparable (L). L''ogre réalise une attaque avec un dé bonus et garde le meilleur résultat. S''il obtient 15-20 au d20 d''un test d''attaque (même sans utiliser Imparable), il inflige +1d6 DM et l''attaque est automatiquement réussie (quelle que soit la DEF de son adversaire).\"}', '[{\"name\":\"Hachoir\",\"test\":\"+7\",\"dm\":\"2d6+6\",\"special\":null,\"reach\":null}]', '[]', NULL, 'Humanoïde', NULL, NULL, 'Grande', '[\"FOR\"]', (SELECT id FROM creature_family WHERE name = 'Ogres'))");
        $this->addSql("INSERT INTO creature (name, description, nc, hp, def, init, stats, special_abilities, attacks, capabilities, picture, category, environment, archetype, size, stats_superior, family_id) VALUES ('Orc de base', 'Les orcs sont des créatures robustes, un peu plus grandes que les humains, dotées de traits bestiaux et habituellement violentes. Ils vivent en tribus sous la domination d''un chef qui règne par la loi du plus fort. Les orcs parlent le noir parler.', 0.5, 12, 13, 10, '{\"AGI\":0,\"CON\":2,\"FOR\":2,\"PER\":0,\"CHA\":-2,\"INT\":-2,\"VOL\":-1}', '{\"text\":\"Sensible à la lumière. Créatures souterraines, les orcs détestent la lumière du jour. La lumière du soleil leur inflige un dé malus en attaque.\"}', '[{\"name\":\"Hache ou masse\",\"test\":\"+3\",\"dm\":\"1d8+2\",\"special\":null,\"reach\":null}]', '[]', NULL, 'Humanoïde', NULL, NULL, 'Moyen', '[\"FOR\"]', (SELECT id FROM creature_family WHERE name = 'Orques'))");
        $this->addSql("INSERT INTO creature (name, description, nc, hp, def, init, stats, special_abilities, attacks, capabilities, picture, category, environment, archetype, size, stats_superior, family_id) VALUES ('Zombie choursette', 'Le zombie choursette voit son NC réduit par rapport à la créature originale, car il a perdu les capacités charge et enragé.', 4, 85, 13, 8, '{\"AGI\":1,\"CON\":6,\"FOR\":6,\"PER\":-2,\"CHA\":-2,\"INT\":-4,\"VOL\":6}', '{\"text\":\"Résistance aux DM. Divisez par deux tous les DM infligés au zombie par des armes, sauf s''il s''agit d''armes tranchantes.\\nSans esprit. Aucune âme n''habite la carcasse morte, le zombie est immunisé à tous les sorts qui affectent l''esprit.\\nLenteur. Le zombie ne se déplace que de 5 m par action de mouvement.\\nInsensible à la douleur. La créature peut encore faire une action (attaque ou mouvement) après avoir été réduite à 0 PV.\"}', '[{\"name\":\"Bec et griffes\",\"test\":\"+12\",\"dm\":\"2d8+10\",\"special\":null,\"reach\":null}]', '[]', NULL, 'Non-vivante', NULL, NULL, 'Grande', '[\"CON\"]', (SELECT id FROM creature_family WHERE name = 'Zombis'))");
        $this->addSql("INSERT INTO creature (name, description, nc, hp, def, init, stats, special_abilities, attacks, capabilities, picture, category, environment, archetype, size, stats_superior, family_id) VALUES ('Chimère draconique', 'La chimère draconique est une cousine de la chimère ordinaire, mais sa tête d''aigle est remplacée par une tête de dragon. Encore plus dangereuse, elle est dotée d''un souffle qui dépend de la couleur de la tête de dragon (rouge pour feu, blanc pour froid, etc.). Elle parle le draconique. Elle possède les mêmes caractéristiques et capacités que la chimère, avec en plus son souffle.', 7, 100, 21, 15, '{\"AGI\":1,\"CON\":6,\"FOR\":6,\"PER\":2,\"CHA\":-4,\"INT\":-2,\"VOL\":2}', '{\"text\":\"Poison. La victime subit 1d6 DM de poison et elle doit faire un test de CON difficulté 16. En cas d''échec, elle subit 1d6 DM supplémentaires par round pendant 5 rounds.\\nRiposte sournoise. Si une créature attaque la chimère dans le dos, la chimère obtient une attaque supplémentaire de serpent contre cet attaquant en plus de ces attaques normales à ce tour.\\nVol rapide. La créature obtient une action de mouvement supplémentaire par round lorsqu''elle est en vol. Au premier round de combat, la créature obtient un dé bonus en attaque et +1d6 aux DM si elle est en vol et attaque une créature au sol.\\nSouffle (L). Le souffle est une attaque de zone affectant toutes les créatures dans un cône de 10 m de long sur 10 m de large. L''attaque inflige automatiquement (pas de test d''attaque) 6d6+9 DM. Les DM sont divisés par deux si la victime réussit un test d''AGI difficulté 15. La créature doit attendre 2d4 rounds avant d''utiliser à nouveau son souffle après chaque utilisation.\"}', '[{\"name\":\"Morsure, bec ou cornes (3 attaques)\",\"test\":\"+14\",\"dm\":\"1d6+6\",\"special\":null,\"reach\":null},{\"name\":\"Morsure de serpent\",\"test\":\"+14\",\"dm\":\"1d4+3 + poison\",\"special\":null,\"reach\":null}]', '[]', NULL, 'Vivante', NULL, NULL, 'Grande', '[\"AGI\",\"PER\"]', NULL)");
    }

    public function down(Schema $schema): void
    {
        // Non réversible : les 147 créatures supprimées ne sont pas restaurées (leur
        // contenu venait d'un wiki tiers, pas du livre — les réintroduire romprait le
        // principe même de cette migration). On retire seulement les 9 ajouts.
        $this->addSql("DELETE FROM creature WHERE name = 'Aigle commun'");
        $this->addSql("DELETE FROM creature WHERE name = 'Animal minuscule'");
        $this->addSql("DELETE FROM creature WHERE name = 'Animal très petit'");
        $this->addSql("DELETE FROM creature WHERE name = 'Animal petit'");
        $this->addSql("DELETE FROM creature WHERE name = 'Cheval de guerre'");
        $this->addSql("DELETE FROM creature WHERE name = 'Ogre de base'");
        $this->addSql("DELETE FROM creature WHERE name = 'Orc de base'");
        $this->addSql("DELETE FROM creature WHERE name = 'Zombie choursette'");
        $this->addSql("DELETE FROM creature WHERE name = 'Chimère draconique'");
    }
}
